
name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            keep-outputs = true
            keep-derivations = true
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build and push AMI to AWS
        run: |
          nix build ".#packages.x86_64-linux.bumble"
          nix run github:NixOS/amis#upload-ami -- --image-info ./result/nix-support/image-info.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
